image: python:3.8 
#image: ubuntu:22.04
#image: gricad-registry.univ-grenoble-alpes.fr/cdbenchmark/benchmark/yade:latest

stages:
  - build
  - deploy

variables:
  DOC_DIR: "$CI_PROJECT_DIR/sphinx"

before_script:
  - apt-get update
  - apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    python3-sphinx \
    python3-sphinx-automodapi \
    python3-sphinxcontrib.bibtex \
    texlive \
    texlive-latex-extra \
    latexmk \
    graphviz

build:
  stage: build
  script:
    - cd $DOC_DIR
    - make html
    - make latexpdf
  artifacts:
    paths:
      - build/html
      - build/latex/*.pdf

pages:
  stage: deploy
  script:
    - mv build/html public
    - cp build/latex/*.pdf public/
    - echo "<a href=\"document.pdf\">Download PDF</a>" >> public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
