#image: python:3.8 
#image: ubuntu:22.04

# This is the self-generated image, see Dockerfile and the manual step "docker"
image: gricad-registry.univ-grenoble-alpes.fr/on-dem/model-data:main

variables:
  DOCKER_DRIVER: overlay2

services: 
  - docker:dind

stages:
  - docker
  - build
  - deploy

variables:
  DOC_DIR: "$CI_PROJECT_DIR/sphinx"

docker:
  image: docker
  stage: docker
  when: manual
  script:
    - echo $CI_REGISTRY
    - echo $CI_REGISTRY_IMAGE
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH

build:
  stage: build
  script:
    - cd $DOC_DIR
    - make html
    - make latexpdf
  artifacts:
    paths:
      - $DOC_DIR/build/html
      - $DOC_DIR/build/latex/*.pdf

pages:
  stage: deploy
  script:
    - ls
    - mv $DOC_DIR/build/html public
    - cp $DOC_DIR/build/latex/*.pdf public/
    - echo "<a href=\"document.pdf\">Download PDF</a>" >> public/index.html
  artifacts:
    paths:
      - public
  only:
    - main
